import { type NewsSource } from "./load-headlines";

export const newsSources: readonly NewsSource[] = [
  {
    id: "africanews-en",
    name: "Africanews",
    region: "Africa",
    language: "English",
    languageCode: "EN",
    translationCode: "en",
    feedUrl: "https://www.africanews.com/feed/rss",
    articleHosts: ["www.africanews.com"],
  },
  {
    id: "cbc-top-stories",
    name: "CBC News",
    region: "Americas",
    language: "English",
    languageCode: "EN",
    translationCode: "en",
    feedUrl: "https://www.cbc.ca/webfeed/rss/rss-topstories",
    articleHosts: ["www.cbc.ca"],
  },
  {
    id: "bbc-world",
    name: "BBC News",
    region: "Europe",
    language: "English",
    languageCode: "EN",
    translationCode: "en",
    feedUrl: "https://feeds.bbci.co.uk/news/world/rss.xml",
    articleHosts: ["www.bbc.co.uk", "www.bbc.com"],
  },
  {
    id: "france24-fr",
    name: "France 24",
    region: "Europe",
    language: "French",
    languageCode: "FR",
    translationCode: "fr",
    feedUrl: "https://www.france24.com/fr/rss",
    articleHosts: ["www.france24.com"],
  },
  {
    id: "nhk-japan",
    name: "NHK News",
    region: "East Asia",
    language: "Japanese",
    languageCode: "JA",
    translationCode: "ja",
    feedUrl: "https://www3.nhk.or.jp/rss/news/cat0.xml",
    articleHosts: ["www3.nhk.or.jp"],
  },
  {
    id: "al-jazeera-en",
    name: "Al Jazeera",
    region: "Middle East",
    language: "English",
    languageCode: "EN",
    translationCode: "en",
    feedUrl: "https://www.aljazeera.com/xml/rss/all.xml",
    articleHosts: ["www.aljazeera.com"],
  },
  {
    id: "the-hindu-national",
    name: "The Hindu",
    region: "South Asia",
    language: "English",
    languageCode: "EN",
    translationCode: "en",
    feedUrl: "https://www.thehindu.com/news/national/feeder/default.rss",
    articleHosts: ["www.thehindu.com"],
  },
] as const;
